### ISSUE TITLE
Addon not loading ?

### ISSUE THREAD

**Issue by Xungames** [dobby121289/MMO7#1]
Hi,
can't find MMO7 in my addon list.

Wow 8.0.1.27178

**Comment by dobby121289** [comment]
Hi,

I am currently using the same version and everything seems to be working. 

These files need to be extracted to "[wow installation folder]/Interface/AddOns/CyborgMMO7/"

If the folder within AddOns is named anything other than "CyborgMMO7" it may not show up.

If this does not help let me know.

**Comment by Xungames** [comment]
My folder was MMO7.
Working fine with CyborgMMO7.

Thanks!
